package wire

import (
	"bytes"
	"encoding/hex"
	"strings"
	"testing"
)

func TestAGridPayloadRoundTripsThroughDeflate(t *testing.T) {
	// Repetitive the way a real render grid is, so it actually compresses.
	plain := []byte(`{"type":"output","grid":{"row_spans":[` +
		strings.Repeat(`{"row":0,"column":0,"style_id":1,"text":"hello"},`, 200) + `]}}`)
	encoded := EncodePayload(plain)
	if encoded[0] != PayloadDeflate {
		t.Fatalf("a compressible payload must be tagged deflate, got tag %d", encoded[0])
	}
	if len(encoded) >= len(plain) {
		t.Fatalf("deflate did not shrink the payload: %d -> %d", len(plain), len(encoded))
	}
	back, err := DecodePayload(encoded)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(back, plain) {
		t.Fatal("round trip changed the payload")
	}
}

// An ack is a few dozen bytes; deflating one makes it bigger. A tagged stream
// must never grow a frame, so these fall back to identity.
func TestAnIncompressiblePayloadStaysIdentity(t *testing.T) {
	plain := []byte(`{"type":"ack","seq":7,"ok":true}`)
	encoded := EncodePayload(plain)
	if encoded[0] != PayloadIdentity {
		t.Fatalf("a payload deflate cannot shrink must stay identity, got tag %d", encoded[0])
	}
	if len(encoded) != len(plain)+1 {
		t.Fatalf("identity must cost exactly the tag byte: %d -> %d", len(plain), len(encoded))
	}
	back, err := DecodePayload(encoded)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(back, plain) {
		t.Fatal("round trip changed the payload")
	}
}

func TestAnUnknownCodecTagIsRefused(t *testing.T) {
	if _, err := DecodePayload([]byte{9, 'x'}); err == nil {
		t.Fatal("an unknown codec tag must be refused, not guessed at")
	}
	if _, err := DecodePayload(nil); err == nil {
		t.Fatal("an empty payload must be refused")
	}
}

func TestAnOverlargePayloadIsRefusedRatherThanAllocated(t *testing.T) {
	// A zip bomb: many megabytes of zeroes in a few hundred compressed bytes.
	huge := make([]byte, maxPayloadSize+1)
	encoded := EncodePayload(huge)
	if encoded[0] != PayloadDeflate {
		t.Fatalf("expected the bomb to compress, got tag %d", encoded[0])
	}
	if _, err := DecodePayload(encoded); err != ErrPayloadTooLarge {
		t.Fatalf("want ErrPayloadTooLarge, got %v", err)
	}
}

// The fixture the app's TerminalSocketTest inflates. Go writes raw DEFLATE
// (RFC 1951) with no zlib wrapper, and Java's Inflater expects the wrapper
// unless constructed with nowrap=true -- a mismatch no amount of Go-side
// testing would catch, because both sides would pass alone. This pins the
// exact bytes the two languages have to agree on (invariant 3).
//
// If this test fails after a codec change, the Kotlin fixture in
// TerminalSocketTest.kt must be regenerated from the value it prints.
func TestTheCrossLanguageFixtureIsUnchanged(t *testing.T) {
	const fixturePlaintext = `{"type":"output","grid":{"columns":4,"rows":1,"row_spans":[{"row":0,"text":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}]},"ok":false}`
	encoded := EncodePayload([]byte(fixturePlaintext))
	got := hex.EncodeToString(encoded)

	// Generated by this function; mirrored verbatim in the app's
	// TerminalSocketTest.kt.
	const want = "018488410a02300cc0fe92730f0a9efa1511193a459c76ac1d2a637f97f90173" +
		"4a32884fcd28d6a3f640b8b6db191d9cacf4c7d3d19dd0ece5e8f62747af69edfd" +
		"58856e84c8ef40497f601ea66077f4928ae7f90d0000ffff"

	if got != want {
		t.Fatalf("codec output changed; regenerate the Kotlin fixture from:\n%s", got)
	}
	back, err := DecodePayload(encoded)
	if err != nil || string(back) != fixturePlaintext {
		t.Fatalf("fixture does not round trip: %v", err)
	}
}
